# Config for single device LoRA finetuning in lora_finetune_single_device.py
# using a Llama2 7B model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Llama-2-7b-hf --output-dir /tmp/Llama-2-7b-hf --hf-token <HF_TOKEN>
#
# To launch on a single device, run the following command from root:
#   tune run lora_finetune_single_device --config llama2/7B_lora_single_device
#
# This config works only for training on single device.

# Model Arguments
model:
  _component_: torchtune.models.llama2.lora_llama2_7b
  lora_attn_modules: ['q_proj', 'v_proj']
  apply_lora_to_mlp: False
  apply_lora_to_output: False
  lora_rank: 8
  lora_alpha: 16

tokenizer:
  _component_: torchtune.models.llama2.llama2_tokenizer
  path: /work1/sinclair/crhowarth/minos-classification-sc25-artifact/datasets/llama2_ft/tokenizer.model

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: /work1/sinclair/crhowarth/minos-classification-sc25-artifact/datasets/llama2_ft
  checkpoint_files:
    - pytorch_model-00001-of-00002.bin
    - pytorch_model-00002-of-00002.bin
  adapter_checkpoint: null
  recipe_checkpoint: null
  output_dir: /work1/sinclair/crhowarth/minos-classification-sc25-artifact/datasets/llama2_ft
  model_type: LLAMA2

resume_from_checkpoint: False

# Dataset and Sampler
dataset:
  _component_: torchtune.datasets.alpaca_cleaned_dataset
seed: null
shuffle: True
batch_size: 64

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  weight_decay: 0.01
  lr: 3e-4

lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torch.nn.CrossEntropyLoss

# Training
epochs: 1
max_steps_per_epoch: 25
gradient_accumulation_steps: 1
compile: True

# Logging
output_dir: /work1/sinclair/crhowarth/minos-classification-sc25-artifact/datasets/llama2_ft
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: /work1/sinclair/crhowarth/minos-classification-sc25-artifact/datasets/llama2_ft
log_every_n_steps: 1
log_peak_memory_stats: False

# Environment
device: cuda
dtype: bf16
enable_activation_checkpointing: True

# Profiler (disabled by default)
profiler:
  _component_: torchtune.utils.setup_torch_profiler
  enabled: False
  output_dir: /work1/sinclair/crhowarth/minos-classification-sc25-artifact/datasets/llama2_ft/profiling_outputs
  cpu: True
  cuda: True
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False
  wait_steps: 100
  warmup_steps: 100
  active_steps: 100
  num_cycles: 1
